minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - asyncmux
  - fast-utf8
  - maypromise
  - call-fn-once
  - inspect-lite
  - abort-signal-utils
  - "@tai-kun/valibot-extra-lab"
onlyBuiltDependencies: []
strictDepBuilds: false
blockExoticSubdeps: true
trustPolicy: no-downgrade
packages:
  [
    "packages/testcontainer",
    "packages/core",
    "packages/utils",
    "packages/checksum",
    "packages/compression",
    "packages/memory",
    "packages/fs.node",
    "packages/s3.node",
    "packages/opfs",
    "packages/indexeddb",
    "unikvs",
  ]
