[settings]
minimum_release_age = "7d"

[tools]
node = "24"
pnpm = "10"
rustfs = "1.0.0-rc.5"

[tasks.test]
run = [{ task = "test:format" }]
env = { CI = 1 }

[tasks."test:format"]
run = { task = "format", args = ["--check"] }

[tasks.format]
run = "set -e; cp ./.config/.oxfmtrc.json ./.tmp-oxfmtrc.json; trap 'rm -f ./.tmp-oxfmtrc.json' EXIT; npx oxfmt --config ./.tmp-oxfmtrc.json"

[tasks.update]
run = [
  "npx npm-check-updates --target minor -u --cooldown 7",
  "pnpm install",
  "for d in $(jq -r '.workspaces[]' package.json | xargs ls -d); do (cd \"$d\" && mise run update); done",
  "pnpm audit",
]
