[tasks.test]
run = [
  { task = "test:client" },
  { task = "test:format" },
  { task = "test:lint" },
  { task = "test:typecheck" },
]
env = { CI = 1 }

[tasks."test:client"]
run = "npx vitest --config ./.config/vitest.client.ts"

[tasks."test:format"]
run = { task = "format", args = ["--check"] }

[tasks."test:lint"]
run = { task = "lint" }

[tasks."test:typecheck"]
run = [
  "npx tsc --noEmit --project ./.config/tsconfig.base.json",
  "npx tsc --noEmit --project ./.config/tsconfig.test.json",
  "npx tsc --noEmit --project ./.config/tsconfig.client.json",
  "npx tsc --noEmit --project ./.config/tsconfig.config.json",
]

[tasks.format]
run = "set -e; cp ./.config/.oxfmtrc.json ./.tmp-oxfmtrc.json; trap 'rm -f ./.tmp-oxfmtrc.json' EXIT; npx oxfmt --config ./.tmp-oxfmtrc.json"

[tasks.lint]
run = "set -e; cp ./.config/.oxlintrc.json ./.tmp-oxlintrc.json; trap 'rm -f ./.tmp-oxlintrc.json' EXIT; npx oxlint --config ./.tmp-oxlintrc.json"

[tasks.update]
run = [
  "npx npm-check-updates --target minor -u --cooldown 7",
  "pnpm install",
  "npx playwright install --with-deps",
]
